### ISSUE TITLE
Db creation failure:  error: near ",": syntax error 

### ISSUE THREAD

**Issue by baranowb** [gerbera/gerbera#1475] opened 2021-05-25 18:01 UTC
May 25 19:50:53 hades gerbera[10957]: 2021-05-25 19:50:53  error: prematurely shutting down.
May 25 19:50:53 hades gerbera[10957]: 2021-05-25 19:50:53  error: No such object: [/builddir/build/BUILD/gerbera-1.8.1/src/database/sqlite3/sqlite_database.cc:338] select Error: [/builddir/build/BUILD/gerbera-1.8.1/src/database/sqlite3/sqlite>
May 25 19:50:53 hades gerbera[10957]: Query: SELECT "f"."id", "f"."ref_id", "f"."parent_id", "f"."object_type", "f"."upnp_class", "f"."dc_title", "f"."location", "f"."location_hash", "f"."metadata", "f"."auxdata", "f"."resources", "f"."update>
May 25 19:50:53 hades gerbera[10957]: error: near ",": syntax error

F34 server
yum install gerbera
systemctl start gerbera

gerbera --compile-info

Gerbera UPnP Server 1.8.1
Copyright 2016-2021 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_MAGIC=1
WITH_MYSQL=1
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=0
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=1
WITH_SYSTEMD=1
WITH_LASTFM=NO
WITH_DEBUG=YES
WITH_TESTS=NO

**Comment by KarlStraussberger** [comment] 2021-05-25 18:30
That doesn't look good.

Your log doesn't show the first error, so let's try with disabling transactions: https://docs.gerbera.io/en/stable/config-server.html#storage

**Comment by baranowb** [comment] 2021-05-26 06:06
Ok, will try once Im done with regular stuff. Thanks.

**Comment by baranowb** [comment] 2021-05-26 14:28
Indeed, this does the trick.

2021-05-26 16:24:30 warning: Sqlite3 database seems to be corrupt or doesn't exist yet.
2021-05-26 16:24:30   info: No sqlite3 backup is available or backup is corrupt. Automatically creating new database file...
2021-05-26 16:24:30   info: database created successfully.
2021-05-26 16:24:30   info: About to migrate metadata from mt_cds_object to mt_metadata
2021-05-26 16:24:30   info: No data will be removed from mt_cds_object
2021-05-26 16:24:30   info: Migrated metadata - object count: 0
2021-05-26 16:24:30   info: Loading 0 configuration items from database
2021-05-26 16:24:30   info: Initialising UPnP with interface: <unset>, port: <unset>
2021-05-26 16:24:30   info: IPv4: Server bound to: XXX
2021-05-26 16:24:30   info: IPv6: Server bound to: XXX
2021-05-26 16:24:30   info: IPv6 ULA/GLA: Server bound to: :49153
2021-05-26 16:24:30   info: The Web UI can be reached by following this link: http://XXX:49152/

Im able to browse DB in web UI and add items.

Unless install script/default value should be changed I think this ticket can be closed?>

**Comment by KarlStraussberger** [comment] 2021-05-26 14:36
The issue is already fixed (#1448) and will be included in the upcoming 1.8.2

**Comment by KarlStraussberger** [comment] 2021-05-26 14:36
Thank you for your help.

**Closed by KarlStraussberger** 2021-05-26 14:36 UTC
