### ISSUE TITLE
Gerbera fails while trying to migrate database after upgrade

### ISSUE THREAD

**Issue by trex2000** [gerbera/gerbera#3237] opened 2024-10-02 13:42 UTC
Hello,
I just upgraded my Ubuntu server to latest Ubuntu 24.04.1 LTS version.
Since then Gerbera is not starting.
Investigating the logs, it looks like it tries to migrate the database, but the Query is failing:
[gerbera.log](https://github.com/user-attachments/files/17230224/gerbera.log)

**Comment by trex2000** [comment] 2024-10-02 13:43
I've attached the log file.
The version that is causing the issue is:
./gerbera -v

Gerbera UPnP Server 2.0.0
Copyright 2016-2023 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

**Comment by KarlStraussberger** [comment] 2024-10-02 16:43
Seems that you are stuck because the first migration failed and left a broken state.

Anyway, you see to be updating from a really old version, so it's better to drop the database and have it recreated from scratch. There were many changes that require a fresh import to benefit from.

Second, I would recommend changing to our repo (see docs) to get the latest version (2.3).

**Comment by trex2000** [comment] 2024-10-03 06:41
I would really not drop the database as I am using gerbera to stream radio stations (and recode them) to the home network and there were quite some entries there. Is there a manual way to edit the sql database ?
Note: It could not be that old, I periodically upgrade the Ubuntu server to LTS versions.

**Comment by trex2000** [comment] 2024-10-03 13:06
I gave up and created everything from scratch, I've purged all configs and reinstalled.
(Note: I tend to not use custom PPAs, just what comes with the LTS package, for stability reasons)
Gerbera starts up, webif is accessible (I've generated a brand new config but enabled the UI, and account)
Now the problem is that the main interface does come up, but as soon as I press the login button, I get the 404 errror.
I've cleared cache, tried on different computers, also tried browsers, incognito mode, etc.
The logs show nothing.
What could be wrong ?

**Comment by trex2000** [comment] 2024-10-03 13:07
![image](https://github.com/user-attachments/assets/84d97fb8-6495-4da3-a0bf-3f262f6fc87c)

**Comment by trex2000** [comment] 2024-10-03 13:07
![image](https://github.com/user-attachments/assets/41e84c7b-b92a-4dfb-962f-67b93b8664b2)

**Comment by KarlStraussberger** [comment] 2024-10-03 15:39
> I would really not drop the database as I am using gerbera to stream radio stations (and recode them) to the home network and there were quite some entries there. Is there a manual way to edit the sql database ?
> Note: It could not be that old, I periodically upgrade the Ubuntu server to LTS versions.
> 

Updating the database would have been quite easy. There is a file mysql-upgrade.xml that contains all the statement in the end you only have to set the correct version in the settings table.

**Comment by KarlStraussberger** [comment] 2024-10-03 15:45
> I gave up and created everything from scratch, I've purged all configs and reinstalled.
> (Note: I tend to not use custom PPAs, just what comes with the LTS package, for stability reasons)
> Gerbera starts up, webif is accessible (I've generated a brand new config but enabled the UI, and account)
> Now the problem is that the main interface does come up, but as soon as I press the login button, I get the 404 errror.
> I've cleared cache, tried on different computers, also tried browsers, incognito mode, etc.
> The logs show nothing.
> What could be wrong ?
> 

The LTS packages are mostly outdated - stable only with respect to enterprise apps. We do not patch old versions, we go straight to the next, so custom PPA is more stable than LTS.

Did try some of the suggestion on our troubleshooting page already: https://docs.gerbera.io/en/latest/troubleshooting.html

**Comment by trex2000** [comment] 2024-10-03 20:02
Okay, so I installed from PPA repo the latest version, 2.3.
This one starts, and also can login.
However, when I try to add a new container (radio) it crashes with:

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

Restarting the service , the newly created  container shows up.
I've started adding Radio stations to it, but then I saw in the logs:
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100


and it just crashed again.


I am starting to loose my patience here.
I've been using Mediatomb, then it got discontinued and switched to gerbera for ages. They work rock solid, I forgot it really existed.

Since the upgrade, it looks like there are problems over problems.
Is there a way to somehow install an older version that is simplier and just works for me  ?

Note:I already lost 2 days trying to make this work just to be able to listen to some radio stations on old sony internet radios that only know dlna and mpeg.
I am a programmer myself and I really try to make this work, however it looks to me that this piece of SW just got worse :(

**Comment by trex2000** [comment] 2024-10-03 20:03
Forgot to mention, I started with a fresh database, I've deleted the old one. Fortunately I have a backup and with an SQL3 db editor I can still get the URLs and all the radio stations out of it.

**Comment by KarlStraussberger** [comment] 2024-10-03 20:45
We're sorry for each bug that stays uncovered, but as this is not our full time paid job we rely on people like you to support us in testing and we're spending our free time developing new features.

I was able to reproduce your first crash. The upnp error message is already in discussion (and was in discussion since the local upnp code was given up) and can only be fixed in the upnp lib.

**Comment by trex2000** [comment] 2024-10-04 07:14
Yes, I know that, and I appreciate the help. This is why I also posted here the logs, maybe somebody could help in fixing it.
I am glad you could reproduce it, in case you provide an update, let me know and I can try it out. 
Regarding UPNP, is it used for advertising only or you also query for devices on the network ? Can this be limited somehow from config or command line ?

**Comment by trex2000** [comment] 2024-10-04 07:17
I read on other forums that the libupnp error message could be solved by adding --disable-blocking_tcp_connections while building it.  I did not try to build it myself, but maybe it would be a solution to add to the buildchain also libunpnp and build one of our own ?

**Comment by trex2000** [comment] 2024-10-04 12:36
Also, side question: isn't there something missing from the GUI ?
![image](https://github.com/user-attachments/assets/0ee40a20-747d-4339-92d3-67d0cece6e3b)

**Comment by trex2000** [comment] 2024-10-04 12:37
I see nowhere a possibility to edit or remove these entries. 
In the documentation I see the buttons there, which were also available in the old versions of gerbera that I've been using before.
![image](https://github.com/user-attachments/assets/09dc807b-7828-4467-bb88-8c7820c5f30e)

**Comment by KarlStraussberger** [comment] 2024-10-04 15:01
This issue typically has two reason
- browser cache: clear the gerbera hosts entries and enjoy
- changed directories because of different build layout: see the respective troubleshooting section and purge the old stuff

**Comment by KarlStraussberger** [comment] 2024-10-04 15:05
> I read on other forums that the libupnp error message could be solved by adding --disable-blocking_tcp_connections while building it.  I did not try to build it myself, but maybe it would be a solution to add to the buildchain also libunpnp and build one of our own ?
> 

Normally all distros use this switch, so no problem here.

For the 2.3 release the sad reason is: we're running over the limit because of the web page being routed through gerbera instead of the libupnp miniserver. Therefore, I proposed a PR to the lib so we can increase the value.

**Comment by trex2000** [comment] 2024-10-05 09:19
> This issue typically has two reason
> 
>     * browser cache: clear the gerbera hosts entries and enjoy
> 
>     * changed directories because of different build layout: see the respective troubleshooting section and purge the old stuff
Thanks, reinstalling gerbera did the trick. Probably the webpage was not upgraded for some reason when I switched to 2.3.

**Closed** 2024-10-07 13:00 UTC
