### ISSUE TITLE
Compiler error in Server::upnp_init()

### ISSUE THREAD

**Issue by azwicker** [gerbera/gerbera#150] opened 2017-09-12 07:57 UTC
Hi,

i followed your guide and compiled pupnp from source. I'm using debian stretch.
I got the following compile error:

[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/server.cc.o
/home/andi/build/gerbera/src/server.cc: In member function ‘void Server::upnp_init()’:
/home/andi/build/gerbera/src/server.cc:178:54: error: too few arguments to function ‘int UpnpAddVirtualDir(const char*, const void*, const void**)’
     ret = UpnpAddVirtualDir(virtual_directory.c_str());
                                                      ^
In file included from /home/andi/build/gerbera/src/io_handler.h:35:0,
                 from /home/andi/build/gerbera/src/tools.h:41,
                 from /home/andi/build/gerbera/src/timer.h:36,
                 from /home/andi/build/gerbera/src/autoscan.h:36,
                 from /home/andi/build/gerbera/src/storage.h:42,
                 from /home/andi/build/gerbera/src/content_manager.h:41,
                 from /home/andi/build/gerbera/src/server.cc:40:
/usr/local/include/upnp/upnp.h:2741:17: note: declared here
 EXPORT_SPEC int UpnpAddVirtualDir(
                 ^~~~~~~~~~~~~~~~~
CMakeFiles/libgerbera.dir/build.make:1550: die Regel für Ziel „CMakeFiles/libgerbera.dir/src/server.cc.o“ scheiterte
make[2]: *** [CMakeFiles/libgerbera.dir/src/server.cc.o] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/libgerbera.dir/all“ scheiterte
make[1]: *** [CMakeFiles/libgerbera.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by v00d00** [comment] 2017-09-12 08:15
Hey,

This actually caused by an upstream change that just landed in master (I know as I submitted that patch).

You should build the last tagged release instead (libupnp 1.8.2).

**Closed by v00d00** 2017-09-12 08:15 UTC

**Comment by azwicker** [comment] 2017-09-12 08:32
thanks for your answer, I'll try that.
