### ISSUE TITLE
Playlists are still served

### ISSUE THREAD

**Issue by gerroon** [gerbera/gerbera#172] opened 2017-10-24 15:09 UTC
Hi

I am trying to make Gerbera to ignore playlists files (m3u, pls etc) so that the clients do not get these files when served. So I commented out every playlist extension I can find in the config. I also deleted the Playlist listing in the web ui. But when my player client (it caches listings locally unlike other players) connects and starts grabbing the file listings over folders, I still get hundreds of playlist files.

Maybe there is another way to disable serving playlist files? If not I would like this to be a feature to be added when the devs have time for implementation.

I am not sure if this is a bug or a feature but I thought I would report it anyways.

thanks

**Comment by elmodaddyb** [comment] 2017-10-28 15:02
Hey @gerroon ,

It looks like during **addObject** `mimetype-contenttype` is used to identify valid UPNP type objects....and invalid objects are ignored.

Can you try removing the `<treat>` stanzas for playlist, and start with a clean DB?  Perhaps this will help resolve.

I took a look at the playlist parsing code.  It looks like the following happens when a directory is scanned.

1. Find the `content-type` of the file based on `mimetype-contenttype`
     It looks at the config.xml XPATH to identify the map of mimetypes to map.
     ```
     /import/mappings/mimetype-contenttype
     ```

2. If content-type is `playlist` and `HAVE_JS=1` then run **playlist.js** to import the playlist

In config.xml, I have the default mappings, among others:
```xml
<mimetype-contenttype>
        <treat mimetype="audio/x-mpegurl" as="playlist"/>
        <treat mimetype="audio/x-scpls" as="playlist"/>
</mimetype-contenttype>
```

**Comment by elmodaddyb** [comment] 2017-10-31 03:00
@gerroon - was the **mimetype-contentype** helpful to resolve the playlist issues?

**Comment by gerroon** [comment] 2017-10-31 03:05
Hi

I am sorry, I will try it tonight,

**Comment by elmodaddyb** [comment] 2017-11-01 01:42
No rush at all, I did not have time to reproduce either 🥇

**Comment by gerroon** [comment] 2017-11-01 17:18
Well I remembered that I actually deleted all my playlist from the media library :(  I will try to reproduce it later.

**Comment by v00d00** [comment] 2017-11-11 11:57
Any luck?

**Comment by elmodaddyb** [comment] 2017-11-12 01:49
@v00d00 @gerroon 
I was able to reproduce the behavior and solve by removing the `<treat>` stanzas in configuration for playlists.  Based on the test, it seems if you exclude the proper _mimetypes_ from the `<mimetype-contenttype>`  it will not be added by the Gerbera scan.

I added `<treat>` stanza back to config.xml and everything is picked up and added under the `Playlists` virtual object.

**Comment by gerroon** [comment] 2017-11-12 02:36
@elmodaddyb 
Thanks, I will try it next time. Like I said, I deleted all the playlists from my lib (though I did not want to do that originally).

**Comment by v00d00** [comment] 2017-11-12 12:31
Okay, closing this for now.

Perhaps a nice PR would be adding an "Ignore playlists" option to the configuration file.

**Closed by v00d00** 2017-11-12 12:31 UTC

**Comment by elmodaddyb** [comment] 2017-11-12 14:33
I think this **ignore** capability is availble in a complicated yet logical way through configuration.  Some usability improvements definitely desirable.

`<extension-mimetype ignore-unknown="no">`  

If set `ignore-unknown=yes` and then remove `*.pls` and `*.m3u` from the list of extensions, these files will get ignored as `unknown` when the system scans the directory for virtual objects.

See [content_manager.cc](https://github.com/gerbera/gerbera/blob/master/src/content_manager.cc#L1154)

Folder-based ignore would be a cool option, but would take some inflated configuration stored in DB or something...
