### ISSUE TITLE
V1.10.0 Web UI Doesn't show the Gerbera server name any more

### ISSUE THREAD

**Issue by BobManMasher** [gerbera/gerbera#2522] opened 2022-03-29 09:00 UTC
Just testing V1.10.0 and the first thing I have noticed was a much faster and cleaner web ui but the name of the server is nowhere to be seen.  It used to be in the title bar after the icon and the word gerbera in the 'Home [server name] field before 'database'.

I also noticed that clicking on the word Gerbera takes you to the Web UI home instead of the GIT like it used to.  Don't know if this was always part of the plan for cleaning up the UI.

I know it's unusiual to have more than one server but I have a live and testing server andit's really easy to get confused between the two sometimes.  Is it possible to get this back on the next rev please.

**Comment by whyman** [comment] 2022-03-29 09:41
Good point, looks like a regression when https://github.com/gerbera/gerbera/pull/2408 was merged

**Closed** 2022-03-29 21:09 UTC
