### ISSUE TITLE
transcoding of ogg not working under ubuntu 18.04

### ISSUE THREAD

**Issue by cot-al** [gerbera/gerbera#308] opened 2018-05-27 11:24 UTC
it was working fine with mediatomb under 17.10, but since I changed it is not working anymore. yet I am using teh same config.xml, vlc and ogg123 are working

**Comment by v00d00** [comment] 2018-05-27 13:08
Can you post a lot with debug log level?

**Comment by cot-al** [comment] 2018-05-27 13:40
Yes of course just let me know how to get this log

**Comment by elmodaddyb** [comment] 2018-05-27 15:57
Hello,

I made some progress on this issue, although encountered the same issue as @cot-al .

1. Installed latest `bionic` release of ubuntu onto docker
2. Compiled latest `gerbera`, everything works OK

3. Enable **transcoding**
   ```xml
    <profile name="oggflac2raw" enabled="yes" type="external">
        <mimetype>audio/L16</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <agent command="ogg123" arguments="-d raw -o byteorder:big -f %out %in"/>
        <buffer size="1048576" chunk-size="131072" fill-size="262144"/>
      </profile>
   ```

### Problems
Transcoding is working OK, but the `ogg123` command line tool is the problem.  When outputting `RAW` format, the `audio/ogg` file is somehow transcoded into an **image** type.

I tested locally, just to eliminate **gerbera**

```
ogg123 -v -d raw -o byteorder:big -f test.pcm /development/gerbera/ogg/test.ogg
```
> this produces complete garbage file, when played is video feedback

I tried this on both Fedora & Ubuntu, and results are the same.

### Summary
It looks like `ogg123` is not actually producing a **RAW** audio file.  Checking the `vorbis-tools` repository looks like it hasnt seen active development for years.

> Perhaps we need to find a suitable replacement for `ogg123`

It is strange that `ogg123` is not working...but there really isnt much conversation about this utility since early 2000.

**Comment by elmodaddyb** [comment] 2018-05-27 17:56
Hello,

I was able to stream an OGG file from Gerbera using the transcoding profile with **vlc**
```xml
<transcoding enabled="yes">
  <mimetype-profile-mappings>
    <transcode mimetype="audio/ogg" using="oggflac2raw"/>
  </mimetype-profile-mappings>
  <profiles>
    <profile name="oggflac2raw" enabled="yes" type="external">
      <mimetype>audio/mpeg</mimetype>
      <accept-url>yes</accept-url>
      <first-resource>yes</first-resource>
      <accept-ogg-theora>yes</accept-ogg-theora>
      <agent command="vlc" arguments="-I dummy %in --sout #transcode{acodec=mp3,channels=2,samplerate=44100}:standard{access=file,mux=raw,dst=%out}"/>
      <buffer size="2500000" chunk-size="512000" fill-size="1024000"/>
    </profile>
</transcoding>
```

When opening the URL directly, Gerbera streams it using VLC until it is done with the file.
`http://localhost:49152/content/media/object_id/69339/res_id/none/pr_name/oggflac2raw/tr/1/ext/file.mp3`
It works well, but tested on PS4 Media player, it does not stream the mp3, on VLC players it picks up the OGG `<res>` instead...so not sure this is a complete fix.

> Let me know if you have success.

**Comment by cot-al** [comment] 2018-05-27 18:55
Thanks!
After your </profile> the tag </profiles> is missing.
Fixing this, the service starts
--- but the onkyo amp cannot read the file, the title is displayed, but no sound... files encoded in mp3 can be read, so the server works, but not the transcoding...
So not a fix for me...

**Comment by elmodaddyb** [comment] 2018-05-28 01:09
@cot-al - I too tried FFMPEG with this setting...which successfully transcodes the file.
```xml
<agent command="ffmpeg" arguments="-y -i %in -f mp3 %out"/>
```
But, hit the same problem.  File runs well when retrieved directly, but fails in UPNP renderers.

I wiresharked the traffic, and the output of the transcoded file is very different than a normal audio file.  The media renderer eventually reports a `TCP RST` (tcp reset) and causes the connection to reset...so the audio never starts playing.

### Transcoded File Response
```
HTTP/1.0 200 OK
CONTENT-TYPE: audio/mpeg
DATE: Mon, 28 May 2018 00:04:48 GMT
LAST-MODIFIED: Sun, 27 May 2018 14:05:51 GMT
SERVER: Linux/4.16.7-200.fc27.x86_64, UPnP/1.0, Portable SDK for UPnP devices/1.8.3
X-User-Agent: redsonic
Content-Disposition: attachment; filename="file.mpg"
```

### File Response
```
HTTP/1.1 206 Partial Content\r\n
CONTENT-LENGTH: 10331033
Accept-Ranges: bytes
CONTENT-TYPE: audio/mpeg
CONTENT-RANGE: bytes 0-10331032/10331033
DATE: Mon, 28 May 2018 00:20:34 GMT
LAST-MODIFIED: Sat, 12 Sep 2015 02:47:53 GMT
SERVER: Linux/4.16.7-200.fc27.x86_64, UPnP/1.0, Portable SDK for UPnP devices/1.8.3
X-User-Agent: redsonic
Content-Disposition: attachment; filename="file.mp3"
Accept-Ranges: bytesCONNECTION: close
```

It might be that UPNP buffers the files differently than direct file stream, but I don't yet understand why the file is properly transcoded, and served by HTTP.  However media renderer cannot play it.

> Still more to figure out...

**Comment by cot-al** [comment] 2018-05-28 19:15
hum and with opus encoder?

**Comment by cot-al** [comment] 2018-05-30 19:53
sorry, but it looks like i am using the latest version : https://xiph.org/downloads/
so problem pending..

**Comment by elmodaddyb** [comment] 2018-05-30 22:23
Hello, I too tried `vorbis-tools` without success.  I suspect the issue is with the HTML protocol with the audio file.  Gerbera does not send the streaming audio any differently than the streaming video...but UPNP renders handle the loading of video properly.

In this case, audio fails to process on the UPNP renderer and that side returns a bunch of TCP RESETS

When time permits, I will look to see if old MEDIATOMB handled transcoded audio data differently than video.  This may reveal the different way to handle it.

I suspect the difference is in the way `libupnp` handles the response data. (i.e. 206 partial content vs. 200 OK).

**Comment by elmodaddyb** [comment] 2018-05-31 00:30
# PROGRESS!!
Hello All,

Great news, I was able to get the Media Renderer to play the transcoded audio stream.

```
<profile name="ogg2mp3" enabled="yes" type="external">
  <mimetype>audio/mpeg</mimetype>
  <accept-url>no</accept-url>
  <first-resource>yes</first-resource>
  <hide-original-resource>yes</hide-original-resource>
  <accept-ogg-theora>no</accept-ogg-theora>
  <agent command="ffmpeg" arguments="-y -i %in -f mp3 %out"/>
  <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
</profile>
```

I added the `Accept-Ranges: bytes` header to the **get-info** response of the Transcoded media...using the patch below:

[https://gist.github.com/elmodaddyb/34f4a6ca9bf1ce676637d249f3f176e7](https://gist.github.com/elmodaddyb/34f4a6ca9bf1ce676637d249f3f176e7)

### Works on:

* VLC @ macOS, Linux, tvOS, iOS
* PlugPlayer @ iOS

### Does NOT work:
* PS4 Media Player
* PS3 Media Player

### Not a complete solution
1. Technically, there is no support for **seek** in transcoded media, since there is no way to know the file size to seek to/from.
2. This patch does not work on ALL media renderers. :-1: 
3. PS3 requires filename extension to match supported types

Any help to test on other renders would be greatly appreciated.

Thanks,

Eamonn

**Comment by cot-al** [comment] 2018-05-31 17:27
Aaah I am interested.
Sorry I am not good at compiling code and so on...
Can you provide me a deb file (or something easy to handle) and I can try tour patch on my ubuntu distrib?
Thanks

**Comment by cot-al** [comment] 2018-05-31 17:46
Hi again,
I found this peace of code in the config.xml here https://doc.ubuntu-fr.org/mediatomb

```
    <!--
       Uncomment the lines below to get rid of jerky avi playback on the
       DSM320 or to enable subtitles support on the DSM units
    -->
    ```
<custom-http-headers>
      <add header="X-User-Agent: redsonic"/>
      <add header="transferMode.dlna.org: Streaming"/>
      <add header="contentFeatures.dlna.org: DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=017000 00000000000000000000000000"/>
    </custom-http-headers>
```
I wonder if we cannot simply change something here without downloading any lib?

**Comment by elmodaddyb** [comment] 2018-06-01 03:41
**OK, I think I may have stumbled onto the easiest solution for this. After staring at the HTTP traces for a few hours!!**

In the current code, the attachment filename is not terminated with `\r\n`, so the next line will get added like.

```http
Content-Disposition: attachment; filename="file.mp3"Accept-Ranges: bytes
```

If I add `\r\n` to the HTTP message.  The file plays accordingly.

```http
Content-Disposition: attachment; filename="file.mp3"\r\n
```

The patch is simply:
```cpp
header = _("Content-Disposition: attachment; filename=\"")
                + path.substring(slash_pos) + _("\"\r\n");
```

I tried rolling back to old code, and file does not play....add back the `\r\n` and the file starts playing.

> There is still some issues with the UPnP browse message when sent to PS3/4 media player...whereby the transcoded media is not represented as playable MP3s.

The solution for strict media renderers will take a bit more thinking, but I think I have all the evidence now! :mag:

**Comment by cot-al** [comment] 2018-06-02 07:31
Ok, how can I use this fix?

**Comment by cot-al** [comment] 2018-06-02 08:47
Hi 
I tried to add tis in config.xml, 
it did not help
```
     <custom-http-headers>
      <add header="Accept-Ranges: bytes"/>
    </custom-http-headers>
```

**Comment by elmodaddyb** [comment] 2018-06-02 13:05
Hello @cot-al - The add custom headers feature is still pending upstream changes in `pupnp`, I do not think it will work appropriately.

As for the fix.  I am working on the unit test and should have a PR in the next few days.  If you are not compiling gerbera from source, we would have to figure out how to build a package.

**Comment by cot-al** [comment] 2018-06-02 15:51
Excellent. Thank you very much. Let me know when you have a deb package ready. I will test it.

**Comment by elmodaddyb** [comment] 2018-06-03 22:02
Fixes are done for this and in a local branch.  I will test a few different transcode profiles then submit a PR.

**Comment by cot-al** [comment] 2018-06-09 09:11
Hello,
Any deb file to test?
Thanks

**Comment by elmodaddyb** [comment] 2018-06-09 12:38
@cot-al - Sorry for the delay, I completed all the code changes for the fix.  I plan to work on the PR and deb file this weekend.

**Comment by cot-al** [comment] 2018-06-09 13:10
no problem. i appreciate a lot  your work and your efforts!

**Comment by cot-al** [comment] 2018-06-16 17:47
sorry for being pushy, is there a deb file I can try somewhere?
Many thanks

**Comment by elmodaddyb** [comment] 2018-06-17 08:51
Hello @cot-al,

Which version of Debian is a good version to test the package. I will spin up a VM to build and test it before sharing. 

Thanks,

Eamonn

**Comment by cot-al** [comment] 2018-06-17 20:41
Hello if you can make a deb file compatible with Ubuntu 18.04 I can try it on my computer. Thanks

**Comment by elmodaddyb** [comment] 2018-06-27 11:11
@cot-al - Sorry for the delay.  I have to find some time to create the ubuntu packages.

> I am working to automate the package building...so its taking a bit more time.

**Comment by cot-al** [comment] 2018-07-03 21:03
Hello, do you think it will be fixed for my party this week-end?
;-))

**Comment by elmodaddyb** [comment] 2018-07-03 21:11
Oh no, sorry for the delay. I have been caught up in some other stuff lately. I am not sure I can get it done by then.

**Comment by elmodaddyb** [comment] 2018-07-04 18:11
@cot-al - I tried to create 3 ubuntu packages  - libupnp, taglib, gerbera.  Unfortunately this was the result on my VM.
```
Segmentation Fault (core dumped)
```

I need to do some more work to understand what I did incorrectly, or which libs are missing.
⛑

**Comment by cot-al** [comment] 2018-07-04 18:34
thank for having tried!

**Comment by cot-al** [comment] 2018-11-12 14:36
Hello
I upgraded to ubuntu 18.10..; you you upload teh bug fix?
Christophe

**Comment by elmodaddyb** [comment] 2018-11-13 04:03
Hello,

Sorry for the lack of response. I previously failed to compile latest 1.3alpha as an Ubuntu packages, my experience is limited with the process. 

I will try again later this week. 

> if you can compile the master branch, the fix is there since 83ad73529fa5d8b261618b5792b9fc9517b2470c

**Comment by v00d00** [comment] 2018-12-23 20:20
Will be fixed in 1.3

**Closed by v00d00** 2018-12-23 20:20 UTC

**Comment by cot-al** [comment] 2019-07-28 15:08
Hi, 
I upgraded to Ubuntu 10.04 still not working??!
Thanks

**Comment by v00d00** [comment] 2019-07-29 08:12
@cot-al which version of gerbera are you running?

**Comment by cot-al** [comment] 2019-07-29 16:28
1.2.0-1~ppa4.1

**Comment by v00d00** [comment] 2019-07-29 19:26
Well, as I mentioned

> Will be fixed in 1.3

The version in the [PPA](https://launchpad.net/~stephenczetty/+archive/ubuntu/gerbera-updates?field.series_filter=disco) is `1.3.2`?

Not sure why you havent got the latest version.

**Comment by cot-al** [comment] 2019-07-31 21:15
Correct, with upgrade PPA was disabled. Now using 1.3.2.
Butstill having trouble. :-(
See my config.xml
`<transcoding enabled="yes">
    <mimetype-profile-mappings>
      <transcode mimetype="video/x-flv" using="vlcmpeg"/>
      <transcode mimetype="application/ogg" using="oggflac2raw"/>
      <transcode mimetype="application/ogg" using="vlcmpeg"/>
      <transcode mimetype="audio/x-flac" using="oggflac2raw"/>
    </mimetype-profile-mappings>
    <profiles>
      <profile name="oggflac2raw" enabled="yes" type="external">
        <mimetype>audio/L16</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
	<hide-original-resource>no</hide-original-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
	<use-chunked-encoding>yes</use-chunked-encoding>
        <agent command="ogg123" arguments="-d raw -o byteorder:big -f %out %in"/>
        <buffer size="1048576" chunk-size="131072" fill-size="262144"/>
      </profile>
      <profile name="vlcmpeg" enabled="no" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit"/>
        <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
      </profile>
    </profiles>
  </transcoding>`
Thanks

**Comment by cot-al** [comment] 2019-09-14 09:20
Any idea about what to do to have transcoding working properly with ubuntu?

**Comment by cot-al** [comment] 2019-11-09 16:52
I updated UBUNTU to 19.04. The version in the distrib is 1.3.2-1~ppa1
Still not working :-(
