### ISSUE TITLE
gerbera 2.3.0 - No Container parent for Item

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#3279] opened 2024-11-22 20:06 UTC
_Originally posted by @nobanzai in https://github.com/gerbera/gerbera/issues/2971#issuecomment-2274115320_

**Comment by KarlStraussberger** [comment] 2024-11-22 21:28
As I learned that your playing around with an import script, you should run a full reimport.

**Comment by nobanzai** [comment] 2024-11-22 21:32
I did that more than one time, but the problem stays.
The messages reappear on every restart of gerbera.

**Comment by KarlStraussberger** [comment] 2024-11-22 22:23
What's the file system structure around? What is the autoscan directory? Did modify the playlist script functions?
We need as much context information as you can provide.

**Comment by nobanzai** [comment] 2024-11-23 10:14
- I didn't modify the playlist import function.
- Autoscan directory for the playlists looks like
```
        <directory
          location="/home/archiv/sound/Michaels_PlayLists/"
          mode="inotify"
          recursive="yes"
          dirtypes="no"
          hidden-files="no"
        />
```
- The playlist files exist in this directory in a plain list, no subdirectories.

**Comment by KarlStraussberger** [comment] 2024-11-26 08:23
I was not able to reproduce the error message, but found some inconsistence in path handling: The trailing slash may cause some trouble.

**Comment by KarlStraussberger** [comment] 2024-11-26 08:24
Can you try out the fix before merging it?

**Comment by nobanzai** [comment] 2024-11-26 09:26
I would, but I guess, there is no ready to install rpm?
Yet I have never built gerbera myself. If I find the time today, I'll try.

**Comment by nobanzai** [comment] 2024-11-26 19:05
Tried it, but got:
```
-- Looking for C++ include filesystem - not found
CMake Error at cmake/FindFilesystem.cmake:246 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:409 (find_package)

```
though /usr/include/c++/7/experimental/filesystem exists.

**Comment by KarlStraussberger** [comment] 2024-11-26 19:23
Your compiler is too old if that happens.

**Comment by nobanzai** [comment] 2024-11-26 19:58
I even got it after installing gcc12 - filesystem is still in 12/experimental, though it shouldn't starting with gcc8!?

**Comment by KarlStraussberger** [comment] 2024-11-29 11:34
It's in the prebuild packages now.

**Comment by nobanzai** [comment] 2024-12-10 15:17
> It's in the prebuild packages now.

Nevertheless I tried to compile Gerbera on my openSUSE Leap 15.6 system.
I got to a point, where all requirements for cmake had been fulfilled and I could run make.
But then there was a problem with the ffmpeg version. On Leap 15.6 ffmpeg-7 is the version of choice, but with the according devel packages I get errors when compiling. So I tried with ffmpeg-4 and its devel packages. With them no errors occurred, but instead I get deprecated messages where in version 7 errors came up.
Because I need ffmpeg-7 on this system, it was a temporary state just to test the compilation, but I had to return to version 7 afterwards.
Is there any chance that you modify Gerbera, so that it can compile with ffmpeg-7, too?

**Comment by nobanzai** [comment] 2024-12-11 14:54
After compilation succeeded, I can approve, that this problem is solved in version v2.3.0-56-g5ac4a21a.
I have no more "No Container parent for Item" messages in the log.

**Comment by nobanzai** [comment] 2024-12-11 14:59
Instead I get
```
2024-12-11 15:57:11.912 warning: [items.cc:217] doSearch(): Empty query string
2024-12-11 15:57:11.912 warning: [web_request_handler.cc:205] open(): Web Error: 800 Error: Empty query string
2024-12-11 15:57:14.068 warning: [items.cc:217] doSearch(): Empty query string
2024-12-11 15:57:14.068 warning: [web_request_handler.cc:205] open(): Web Error: 800 Error: Empty query string
2024-12-11 15:57:17.386 warning: [items.cc:217] doSearch(): Empty query string
2024-12-11 15:57:17.387 warning: [web_request_handler.cc:205] open(): Web Error: 800 Error: Empty query string
```

when opening the GUI.

**Comment by KarlStraussberger** [comment] 2024-12-11 22:18
That sounds like an issue with the browser cache

**Comment by nobanzai** [comment] 2024-12-11 23:01
> That sounds like an issue with the browser cache

Nope. Tried with a clean cache in Firefox and with Falcon, where I never used the gerbera web page.

**Comment by cweiske** [comment] 2024-12-19 21:41
I also saw this "Empty query string" in v2.3.0, but it is gone in later commits.

**Comment by KarlStraussberger** [comment] 2024-12-22 16:53
Let's close this issue and open new ones if any of the problems reappear - with clear reproduction steps.

**Closed** 2024-12-22 16:53 UTC

**Comment by nobanzai** [comment] 2024-12-22 19:05
> Let's close this issue and open new ones if any of the problems reappear - with clear reproduction steps.

Not sure, what you mean, but the problem, i mentioned above, still exists.
As I wrote 

> I had to go back the the version from the rpm.
> Besides the mentioned error message, gerbera wasn't able to provide cover art any more.

**Comment by KarlStraussberger** [comment] 2024-12-22 20:35
Switching between distro and self-build is dangerous. Anyway, the issue is a mixed bag of things which we have to sort out.

For your issue, uninstall the rpm, remove all files and the  reinstall. Packages tend to you different folders. See https://docs.gerbera.io/en/lastest/troubleshooting.html#installation

**Comment by nobanzai** [comment] 2024-12-23 10:19
> Switching between distro and self-build is dangerous. Anyway, the issue is a mixed bag of things which we have to sort out.
> 
> For your issue, uninstall the rpm, remove all files and the reinstall. Packages tend to use different folders. See https://docs.gerbera.io/en/lastest/troubleshooting.html#installation

Already did that. Didn't change anything.
