### ISSUE TITLE
follow symlink

### ISSUE THREAD

**Issue by bedenko** [gerbera/gerbera#78] opened 2017-04-25 18:31 UTC
if i would like to add media through symlinked directory, that directory is not visible through web gui.

**Comment by elmodaddyb** [comment] 2017-08-09 00:43
I took a look at the source code that renders out the file system list.  The `files` request handler processes these requests

[web::files::files() : WebRequestHandler()](https://github.com/v00d00/gerbera/blob/master/src/web/files.cc#L42)

The system is using `stat` to read the contents of a given directory, so I think it will follow any symlink to its end (retrieving the destination's file props).  However, when the system is adding the file system object to the array, it is checking for only `S_ISREG` and `S_ISDIR`

[Filesystem::readDirectory](https://github.com/v00d00/gerbera/blob/master/src/filesystem.cc#L148)

So it seems like we need to enhance the [selection](https://github.com/v00d00/gerbera/blob/master/src/filesystem.cc#L170) a bit.

Maybe adding something like below??

```
else if(S_ISLINK(st.st_mode)) {
      // This entry is a symbolic link
      //  Add similar directory logic as with S_ISDIR(statbuf.st_mode)...
}
```
I still need to understand what the `statbuf.st_mode` is when the directory is a symlink...to reconcile this approach.  Eventually need to understand what would happen when you actually `click` the _symlink'd_ folder on the UI

Will keep you posted.

Thanks,

E

**Comment by elmodaddyb** [comment] 2017-08-11 23:22
@bedenko - I was working through this solution, and created new symlink to test it out.
Created symbolic link via the command:
```
$ ln -s /home/other-user/videos/ ./videosOther
```
And it looks like this:
```
lrwxrwxrwx.  1 root   root      20 Aug 10 20:12 videosOther -> /home/other-user/videos/
```
I can see it OK in the `Filesystem` view of the Web GUI, including child videos. 
> This seems right, because gerbera uses `stat` to read the filesystem objects.

I will try a few things with symbolic link permissions to see if it is related to who `owns` the symlink...?

**Do you have additional details that could help with a failing scenario??**

**Comment by elmodaddyb** [comment] 2017-09-12 01:05
I was able to retest this a bit further and found that system is working as expected.

1. Symlinks are available to Gerbera as per the `stat` functionality.
2. Access permissions are respected.
     - A file must be _readable_ and _executable_ by the `gerbera` process for it to launch and play.

I am inclined to close this issue as it appears to be working properly.

@bedenko have you been able to resolve the symlink permissions issues?

**Comment by elmodaddyb** [comment] 2017-09-28 01:24
@v00d00 - I recommend we close this issue. Testing appears to work properly with symlinks and issue has been inactive since April....what do you think?

**Comment by v00d00** [comment] 2017-09-28 07:48
@elmodaddyb sounds sensible to me, do it!

**Comment by elmodaddyb** [comment] 2017-09-30 02:40
Closing issue.  The system code appears to work and provide access to symlink.  If you encounter any issue that reproduces the behavior please reopen.

**Closed by elmodaddyb** 2017-09-30 02:40 UTC
Labels: beginner-friendly, enhancement, help wanted
