### ISSUE TITLE
Thumbnails generation fails (ffmpegthumbnailer)

### ISSUE THREAD

**Issue by piknew** [gerbera/gerbera#3079] opened 2024-05-05 20:19 UTC
Version of Gerbera: 2.1.0

**As I am trying to generate thumbnails for my photos - following errors are reported in log (below). Directory cache-dir is not created.**

```
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.971  debug: [exiv2_handler.cc:86] fillMetadata(): date: 2019-05-18T11:30:37
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.971  debug: [exiv2_handler.cc:101] fillMetadata(): Comment:
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.971  debug: [exiv2_handler.cc:181] fillMetadata(): No aux data requested
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.971  debug: [exiv2_handler.cc:209] fillMetadata(): No aux data requested
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972  debug: [libexif_handler.cc:194] process_ifd(): Found exif date: 2019:05:18 11:30:37
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972  debug: [libexif_handler.cc:209] process_ifd(): Found exif comment:
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972  debug: [libexif_handler.cc:217] process_ifd(): Found exif X dimension: 6000
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972  debug: [libexif_handler.cc:225] process_ifd(): Found exif Y dimension: 4000
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972  debug: [libexif_handler.cc:299] fillMetadata(): EXIF Thumb Resolution: 160x120
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.972 warning: [ffmpeg_thumbnailer_handler.cc:144] fillMetadata(): Failed to generate resource for thumbnail: /share/Public/Photos/Sony/2019/05/2019-05-18_11-30-36_DSC02221.JPG [./src/config/config_manager.cc:497] virtual IntOptionType ConfigManager::getIntOption(config_option_t) const Error: option 60 not set
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [exiv2_handler.cc:86] fillMetadata(): date: 2019-05-18T11:30:42
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [exiv2_handler.cc:101] fillMetadata(): Comment:
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [exiv2_handler.cc:181] fillMetadata(): No aux data requested
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [exiv2_handler.cc:209] fillMetadata(): No aux data requested
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [libexif_handler.cc:194] process_ifd(): Found exif date: 2019:05:18 11:30:42
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [libexif_handler.cc:209] process_ifd(): Found exif comment:
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [libexif_handler.cc:217] process_ifd(): Found exif X dimension: 6000
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [libexif_handler.cc:225] process_ifd(): Found exif Y dimension: 4000
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977  debug: [libexif_handler.cc:299] fillMetadata(): EXIF Thumb Resolution: 160x120
May  5 22:04:04 PKMEDIA gerbera[9943]: 2024-05-05 22:04:04.977 warning: [ffmpeg_thumbnailer_handler.cc:144] fillMetadata(): Failed to generate resource for thumbnail: /share/Public/Photos/Sony/2019/05/2019-05-18_11-30-42_DSC02222.JPG [./src/config/config_manager.cc:497] virtual IntOptionType ConfigManager::getIntOption(config_option_t) const Error: option 60 not set
```

**My config is as following (regarding "ffmpegthumbnailer"):**

```
	<extended-runtime-options>
			<ffmpegthumbnailer enabled="yes">
				<thumbnail-size>160</thumbnail-size>
			</ffmpegthumbnailer>
			<mark-played-items enabled="no" suppress-cds-updates="yes">
				<string mode="prepend">*</string>
				<mark>
					<content>video</content>
				</mark>
			</mark-played-items>
		</extended-runtime-options>
```

FfmpegThumbnailerHandler::fillMetadata ?

**Comment by KarlStraussberger** [comment] 2024-05-05 21:43
I suppose your issue is related to #3064.

Please provide details on your package source and build configuratio  (`--compile.info`)

**Comment by piknew** [comment] 2024-05-06 05:39
Please see as following (the package is installed from deb-multimedia repository):

`[root@PKMEDIA ~]# /usr/bin/gerbera --compile-info

Gerbera UPnP Server 2.1.0
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=1
WITH_MAGIC=ON
WITH_MYSQL=1
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=1
WITH_AVCODEC=OFF
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=ON
WITH_EXIV2=1
WITH_MATROSKA=ON
WITH_WAVPACK=OFF
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF

[root@PKMEDIA ~]#
`

**Comment by KarlStraussberger** [comment] 2024-05-06 10:06
Please try to update to at least version 1:2.1.0-dmo0~bpo12+2. This is a packaging issue.

**Comment by piknew** [comment] 2024-05-08 09:27
@KarlStraussberger, but my report was already for "1:2.1.0-dmo0~bpo12+2", please see as above (where I have given the version):

gerbera/stable-backports,now 1:2.1.0-dmo0~bpo12+2 amd64 [installed]

**Comment by piknew** [comment] 2024-05-08 09:39
And it seems that exception (for warning) is thrown for "ConfigManager::getIntOption" - it seems that "config" reader does not see value 160? It seems that exception is thrown as results of these lines:

```
auto y = config->getIntOption(CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_THUMBSIZE) * resolution.y() / resolution.x();
auto x = config->getIntOption(CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_THUMBSIZE);
```

**Comment by piknew** [comment] 2024-05-08 18:44
I have just simplified my config to point to directory with 2 example photos (one from A6700, one from old Huawei P10 - as I was not sure if maybe the problem is related to content itself). Then I have enabled debug for all items listed in documentation. The result is as follows - unfortunately there is no other message than this "warning" (see lines 462 and 792).

[gerbera.log](https://github.com/gerbera/gerbera/files/15253511/gerbera.log)

So, I think something is strange with these "config" parameters.

**Comment by piknew** [comment] 2024-05-08 18:48
Please also see my full config for this test - the only thing that I did - I just "starred" my <externalURL></externalURL> parameter (as it contains my public domain):

[config.zip](https://github.com/gerbera/gerbera/files/15253543/config.zip)

**Comment by KarlStraussberger** [comment] 2024-05-08 18:53
The problem is still that the package was build with ffmpegthumbnailer but without ffmpeg. We never thought of this so some config options are not fully available but used. This is fixed in HEAD. The package can fix it by enabling ffmpeg/avcodec.

**Comment by piknew** [comment] 2024-05-08 19:34
Thank you - I have compiled gerbera, get it as:
![image](https://github.com/gerbera/gerbera/assets/39850926/da4331c4-5b2a-4883-84fe-0ac8afdeaa67)

Now it seems that it is OK:
![image](https://github.com/gerbera/gerbera/assets/39850926/03671704-a718-4fcd-a3c3-beab87bfda2c)

Just one question - How to add thumbnail to container? As you can see there is 404 for file.jpg - I am attaching also my custom.js script - very simple, but maybe there is an issue: 
[custom.zip](https://github.com/gerbera/gerbera/files/15253925/custom.zip)

![image](https://github.com/gerbera/gerbera/assets/39850926/c5a2a61f-0352-4cd0-8190-db822a88a1a7)

**Closed** 2024-05-08 21:53 UTC
Labels: packaging

**Comment by KarlStraussberger** [comment] 2024-05-09 04:21
we rely on a thumbnail in the image which seems to be broken. Also, there are some cases when - I don't know why - they get lost

**Comment by piknew** [comment] 2024-05-09 10:00
side comment - I have found the issue with lack of thumbnails for containers, the problem was with custom script, fields refID and res have been incorrectly assigned.
