### ISSUE TITLE
Using Ubuntu PPA package with iNotify doesn't seem to be working atm

### ISSUE THREAD

**Issue by Martii** [gerbera/gerbera#545] opened 2019-12-09 17:34 UTC
Heyo,

Currently unable to have iNotify pick up new/renamed .mp4's after the 1.3.5-1 update listed below. I am currently encoding for the last few weeks, so each day I add one or more media files. Before the Ubuntu/Kubuntu update, which was only Gerbera, on the server it was working but now it's not. The media files are of course valid and play in smplayer/vlc/etc.

I attempted to "Delete All" just to see if a prior work-around worked when I first started using Gerbera with re-scanning from scratch. Claims it did work however nothing other than the green status message of complete. Old items are still in DB list, and they do play in the UPnP client but nothing new. Tried in latest Fx and latest Chromium... clean profiles.

File System under the path shows my file but when added shows the status message of success but DB doesn't show it.

Tried rebooting server with no change. I haven't tweaked the configuration at all in about a year or so *(mostly defaults anyways... just port and server "name" changes from historical recall)*.

Let me know if you need any other info. I'd rather not scratch the DB completely and restart from total scratch so any help would be appreciated. :) This is a production machine so I'm not able to build the current HEAD and use it instead of the PPA.

``` console
$ apt-cache madison gerbera
   gerbera | 1.3.5-1~ppa1~bionic1 | http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu bionic/main amd64 Packages
   gerbera | 1.1.0+dfsg-2 | http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

$ uname -a
Linux server 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks for your work on this project. :)

**Comment by whyman** [comment] 2019-12-09 20:14
Can you post a debug log?

**Comment by Martii** [comment] 2019-12-10 02:39
@whyman 

Sure thing. :)

Using:
``` shell
# /usr/bin/gerbera -c /etc/gerbera/config.xml --debug
```

... get this attachment:

[gerbera.debug.log](https://github.com/gerbera/gerbera/files/3942728/gerbera.debug.log)

... and taking a wild stab at an error that seems to be present a few times when I added a single test file:

``` console
error: no such table: main.cds_object
```



... seems like a SQLite3 issue... hope the DB wasn't corrupted/changed at some recent commit by this update because it's been a super long time since I've dabbled with server recreation... which causes a cascade to the client with their rescanning/caching too. :\

**Comment by whyman** [comment] 2019-12-10 16:59
Hey, well the bad news is you can fix it by removing your DB file and recreating it...

This seems to be caused by the fact we now tell sqlite to enforce foreign keys, but there is weird behaviour of you create your tables before you enable the foreign key schema 👎 which is effectively what's happening here.

**Comment by whyman** [comment] 2019-12-10 17:08
The other option is there was a bug in the schema used to create the table.... I will check that

**Comment by whyman** [comment] 2019-12-10 18:38
So there was a schema bug that was fixed in v1.3.3 https://github.com/gerbera/gerbera/commit/2b75c7ec068be5e2d58b374462277499a7fd9584

But we didnt ship an update to existing schemas then, as it didnt break anything.

But then then we turned on the enforcement of the (incorrect) foreign keys in https://github.com/gerbera/gerbera/commit/2ee3fc3cbe2deb5af515c32a8d9b3203180d76f0 which causes the issue.

So anyone who has a database created before `v1.3.3` that could be having a problem if they upgrade.

I guess we will have to write a update in the next release to avoid this happening.

**Comment by whyman** [comment] 2019-12-10 20:12
@Martii  if you can, can you run this SQL against your DB?

You should be able to do it from most DB apps or the [sqlite CLI](https://sqlite.org/cli.html). Make sure you stop Gerbera while doing it.

```sql
PRAGMA foreign_keys = OFF;
CREATE TABLE mt_cds_object_new
(
	id integer
		primary key,
	ref_id integer default NULL
		constraint cds_object_ibfk_1
			references mt_cds_object_new (id)
			 ON update cascade on delete cascade,
	parent_id integer default '0' not null
		constraint cds_object_ibfk_2
			references mt_cds_object_new (id)
			 ON update cascade on delete cascade,
	object_type tinyint unsigned not null,
	upnp_class varchar(80) default NULL,
	dc_title varchar(255) default NULL,
	location text default NULL,
	location_hash integer unsigned default NULL,
	metadata text default NULL,
	auxdata text default NULL,
	resources text default NULL,
	update_id integer default '0' not null,
	mime_type varchar(40) default NULL,
	flags integer unsigned default '1' not null,
	track_number integer default NULL,
	service_id varchar(255) default NULL
);
INSERT INTO mt_cds_object_new(id, ref_id, parent_id, object_type, upnp_class, dc_title, location, location_hash, metadata, auxdata, resources, update_id, mime_type, flags, track_number, service_id) select id, ref_id, parent_id, object_type, upnp_class, dc_title, location, location_hash, metadata, auxdata, resources, update_id, mime_type, flags, track_number, service_id from mt_cds_object;
DROP TABLE mt_cds_object;
ALTER TABLE mt_cds_object_new RENAME TO mt_cds_object;
CREATE INDEX mt_cds_object_parent_id ON mt_cds_object (parent_id, object_type, dc_title);
CREATE INDEX mt_cds_object_ref_id ON mt_cds_object (ref_id);
CREATE INDEX mt_cds_object_service_id ON mt_cds_object (service_id);
CREATE INDEX mt_location_parent ON mt_cds_object (location_hash, parent_id);
CREATE INDEX mt_object_type ON mt_cds_object (object_type);
CREATE INDEX mt_track_number on mt_cds_object (track_number);
PRAGMA foreign_keys = ON;
```

**Comment by Martii** [comment] 2019-12-11 01:57
@whyman 

Thank you very much for the elaborate responses.

So using the CLI *(been a few years and I'm a bit rusty I think :smile_cat: )*...

``` console
$ sudo systemctl stop gerbera
```

... then ...

``` console
$ sudo su
# cd /var/lib/gerbera
# # Backup DB in case of failure for restore
# cp gerbera.db gerbera.backup.db
```

... alternate Try 2 *(redirect stdin with [the pre/code patch](https://github.com/gerbera/gerbera/files/3947956/Issue-545tryFix1.sql.txt) [above](https://github.com/gerbera/gerbera/issues/545#issuecomment-564224736) )*...

``` console
# # Using .txt extension for GitHub upload of .sql pre/code patch reference since it won't accept .sql
# sqlite3 gerbera.db < Issue-545tryFix1.sql.txt
# exit

$ sudo systemctl start gerbera
$ systemctl status gerbera
? gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-12-10 19:24:25 EST; 48s ago
     Docs: man:gerbera(1)
           https://gerbera.io/
 Main PID: 2429 (gerbera)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/gerbera.service
           ??2429 /usr/bin/gerbera -c /etc/gerbera/config.xml

Dec 10 19:24:25 server gerbera[2429]: error: no such table: main.mt_cds_object_new
Dec 10 19:24:25 server gerbera[2429]: Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:392] waitForTask(): SQLITE3
Dec 10 19:24:25 server gerbera[2429]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12346,12347,12348)
Dec 10 19:24:25 server gerbera[2429]: error: no such table: main.mt_cds_object_new
Dec 10 19:24:25 server gerbera[2429]: 2019-12-10 17:24:25   ERROR: Exception caught: SQLITE3: (1 : 1) no such table: main.mt_
Dec 10 19:24:25 server gerbera[2429]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12474,12475,12476)
Dec 10 19:24:25 server gerbera[2429]: error: no such table: main.mt_cds_object_new
Dec 10 19:24:25 server gerbera[2429]: Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:392] waitForTask(): SQLITE3
Dec 10 19:24:25 server gerbera[2429]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12474,12475,12476)
Dec 10 19:24:25 server gerbera[2429]: error: no such table: main.mt_cds_object_new
```

... since copy/paste of [pre/code patch](https://github.com/gerbera/gerbera/files/3947956/Issue-545tryFix1.sql.txt) *(Try 1)* failed with this rather lengthy output:


[Issue-545sql.console.txt](https://github.com/gerbera/gerbera/files/3947973/Issue-545sql.console.txt)



... most notably everywhere where it states:
> "Display all 160 possibilities? (y or n)" 

and the cutoff of `straint`, etc.

> ... can you run this SQL against your DB?

Result seems to be **FAIL** with Try 1 and Try 2. Again I'm quite rusty on this procedure... so bear with me please.

Any fixes for that DB patch, or how I'm doing it? Thanks again.

P.S. Don't mind my outlining the process it's what I do in case I, or perhaps someone else, need to do it again and better with my memory recall.

**Comment by whyman** [comment] 2019-12-11 08:35
Interesting that the self reference doesn't get renamed.... Out of interest, which version of sqlite do you have? They have changed the renaming procedure in recent versions

**Comment by Martii** [comment] 2019-12-11 16:22
> ... which version of sqlite do you have?

It's at the top of the file of [Issue-545sql.console.txt](https://github.com/gerbera/gerbera/files/3947973/Issue-545sql.console.txt) but reconfirmed with apt:

``` console
$ apt-cache madison sqlite3
   sqlite3 | 3.22.0-1ubuntu0.2 | http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
   sqlite3 | 3.22.0-1ubuntu0.2 | http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
   sqlite3 |   3.22.0-1 | http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

... and sqlite3 itself ...

``` console
$ sqlite3
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select sqlite_version();
3.22.0
sqlite>
```

sqlite-tools-linux-x86-3300100 appears to be 3.30.0100 *(or 3.300.100 IDK for sure)* and file dated about 2019-10-11 in their zip... unfortunately the prebuilt Linux binaries don't appear to be functional out of the box, which is weird, but they only seem to offer x86 and not x64 *(minor but could be a factor)*.

**Comment by Martii** [comment] 2019-12-11 17:25
@whyman 

Btw the CLI UI seems to dislike all tab indention in the original patch *(untabbed patch at [Issue-545tryFix1a.sql.txt](https://github.com/gerbera/gerbera/files/3951652/Issue-545tryFix1a.sql.txt))* ... thought it might be this which is the direction I was heading in with Try 2 but wasn't ready :smile_cat: to do Try 3:

``` console
# sqlite3 gerbera.db 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> PRAGMA foreign_keys = OFF;
sqlite> CREATE TABLE mt_cds_object_new
   ...> (
   ...>   id integer
   ...>     primary key,
   ...>   ref_id integer default NULL
   ...>     constraint cds_object_ibfk_1
   ...>       references mt_cds_object_new (id)
   ...>        ON update cascade on delete cascade,
   ...>   parent_id integer default '0' not null
   ...>     constraint cds_object_ibfk_2
   ...>       references mt_cds_object_new (id)
   ...>        ON update cascade on delete cascade,
   ...>   object_type tinyint unsigned not null,
   ...>   upnp_class varchar(80) default NULL,
   ...>   dc_title varchar(255) default NULL,
   ...>   location text default NULL,
   ...>   location_hash integer unsigned default NULL,
   ...>   metadata text default NULL,
   ...>   auxdata text default NULL,
   ...>   resources text default NULL,
   ...>   update_id integer default '0' not null,
   ...>   mime_type varchar(40) default NULL,
   ...>   flags integer unsigned default '1' not null,
   ...>   track_number integer default NULL,
   ...>   service_id varchar(255) default NULL
   ...> );
sqlite> INSERT INTO mt_cds_object_new(id, ref_id, parent_id, object_type, upnp_class, dc_title, location, location_hash, metadata, auxdata, resources, update_id, mime_type, flags, track_number, service_id) select id, ref_id, parent_id, object_type, upnp_class, dc_title, location, location_hash, metadata, auxdata, resources, update_id, mime_type, flags, track_number, service_id from mt_cds_object;
sqlite> DROP TABLE mt_cds_object;
sqlite> ALTER TABLE mt_cds_object_new RENAME TO mt_cds_object;
sqlite> CREATE INDEX mt_cds_object_parent_id ON mt_cds_object (parent_id, object_type, dc_title);
sqlite> CREATE INDEX mt_cds_object_ref_id ON mt_cds_object (ref_id);
sqlite> CREATE INDEX mt_cds_object_service_id ON mt_cds_object (service_id);
sqlite> CREATE INDEX mt_location_parent ON mt_cds_object (location_hash, parent_id);
sqlite> CREATE INDEX mt_object_type ON mt_cds_object (object_type);
sqlite> CREATE INDEX mt_track_number on mt_cds_object (track_number);
sqlite> PRAGMA foreign_keys = ON;
sqlite>
```
<kbd>Ctrl</kbd> + <kbd>D</kbd>

``` console
$ sudo systemctl start gerbera
$ systemctl status gerbera
? gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-12-11 12:04:39 EST; 5s ago
     Docs: man:gerbera(1)
           https://gerbera.io/
 Main PID: 13268 (gerbera)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/gerbera.service
           ??13268 /usr/bin/gerbera -c /etc/gerbera/config.xml

Dec 11 12:04:39 server gerbera[13268]: error: no such table: main.mt_cds_object_new
Dec 11 12:04:39 server gerbera[13268]: Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:392] waitForTask(): SQLITE3: (1 : 1
Dec 11 12:04:39 server gerbera[13268]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12346,12347,12348)
Dec 11 12:04:39 server gerbera[13268]: error: no such table: main.mt_cds_object_new
Dec 11 12:04:39 server gerbera[13268]: 2019-12-11 10:04:39   ERROR: Exception caught: SQLITE3: (1 : 1) no such table: main.mt_cds_obje
Dec 11 12:04:39 server gerbera[13268]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12474,12475,12476)
Dec 11 12:04:39 server gerbera[13268]: error: no such table: main.mt_cds_object_new
Dec 11 12:04:39 server gerbera[13268]: Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:392] waitForTask(): SQLITE3: (1 : 1
Dec 11 12:04:39 server gerbera[13268]: Query:DELETE FROM "mt_cds_object" WHERE "id" IN (12474,12475,12476)
Dec 11 12:04:39 server gerbera[13268]: error: no such table: main.mt_cds_object_new
```

... however still doesn't appear to be making that new table. Even tried the sqlitebrowser gui *(with some OS permission changes of course)* and it doesn't appear to be showing in the Database Structure tab.

So what next perhaps?

**Comment by whyman** [comment] 2019-12-11 17:37
So what should happen is that we create the new table, drop the old one and rename the new back to the original name (all because SQLite doesnt let us edit the foreign key constraints :-1: )

@Martii Can you try it changing `references mt_cds_object_new (id)` to ` references mt_cds_object (id)`

**Comment by Martii** [comment] 2019-12-11 19:01
@whyman 

> ... try it changing ...

Change diff of:

``` diff
--- Issue-545tryFix1a.sql.txt   2019-12-11 11:57:51.223128575 -0500
+++ Issue-545tryFix2a.sql.txt   2019-12-11 12:58:34.707994085 -0500
@@ -5,11 +5,11 @@
     primary key,
   ref_id integer default NULL
     constraint cds_object_ibfk_1
-      references mt_cds_object_new (id)
+      references mt_cds_object (id)
        ON update cascade on delete cascade,
   parent_id integer default '0' not null
     constraint cds_object_ibfk_2
-      references mt_cds_object_new (id)
+      references mt_cds_object (id)
        ON update cascade on delete cascade,
   object_type tinyint unsigned not null,
   upnp_class varchar(80) default NULL,
```

... from [Issue-545tryFix2a.sql.txt](https://github.com/gerbera/gerbera/files/3951914/Issue-545tryFix2a.sql.txt) ...


``` console
# diff -u Issue-545tryFix1a.sql.txt Issue-545tryFix2a.sql.txt 
--- Issue-545tryFix1a.sql.txt   2019-12-11 11:57:51.223128575 -0500
+++ Issue-545tryFix2a.sql.txt   2019-12-11 12:58:34.707994085 -0500
@@ -5,11 +5,11 @@
     primary key,
   ref_id integer default NULL
     constraint cds_object_ibfk_1
-      references mt_cds_object_new (id)
+      references mt_cds_object (id)
        ON update cascade on delete cascade,
   parent_id integer default '0' not null
     constraint cds_object_ibfk_2
-      references mt_cds_object_new (id)
+      references mt_cds_object (id)
        ON update cascade on delete cascade,
   object_type tinyint unsigned not null,
   upnp_class varchar(80) default NULL,

# sqlite3 gerbera.db < Issue-545tryFix2a.sql.txt

# # Cleanup file permissions changed for testing in sqlitebrowser and terminal
# chmod 775 .
# chmod 644 gerbera.db
# chown gerbera:gerbera gerbera.db

# # Return to non-elevated konsole tab below
```

``` console
$ sudo systemctl stop gerbera
$ # Using other konsole tab above here
$ sudo systemctl start gerbera
$ systemctl status gerbera
? gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-12-11 13:00:23 EST; 6s ago
     Docs: man:gerbera(1)
           https://gerbera.io/
 Main PID: 13573 (gerbera)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/gerbera.service
           ??13573 /usr/bin/gerbera -c /etc/gerbera/config.xml

Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Setting filesystem import charset to UTF-8
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Setting metadata import charset to UTF-8
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Setting playlist charset to UTF-8
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Configuration check succeeded.
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: About to migrate metadata from mt_cds_object to mt_metadata
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: No data will be removed from mt_cds_object
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Migrated metadata - object count: 0
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Initialized port: 49152
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: Server bound to: 192.168.0.clipped
Dec 11 13:00:23 server gerbera[13573]: 2019-12-11 11:00:23    INFO: The Web UI can be reached by following this link: http://192.168.0
$
```

Houston! We have successful lift-off! All my .mp4 media files are listed in the UPnP DLNA client now *without* a rescan/recache from them too. :grinning: The patch of [Issue-545tryFix2a.sql.txt](https://github.com/gerbera/gerbera/files/3951914/Issue-545tryFix2a.sql.txt) worked on my second instance as well.

**Major Thanks!** :bowing_man:  Let me know if you need anything else tried out.

**Comment by whyman** [comment] 2019-12-11 20:30
Great, I've updated the query in #546

**Closed** 2019-12-11 20:42 UTC
