### ISSUE TITLE
gerbera 2.3.0 and default for items-per-page

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#3269] opened 2024-11-12 20:32 UTC
gerbera 2.3.0 on openSUSE Leap 15.6

```
      <items-per-page default="50">
        <option>10</option>
        <option>25</option>
        <option>50</option>
        <option>100</option>
      </items-per-page>

```
does show only 25 items per page by default.

**Comment by udippel** [comment] 2024-11-12 22:07
Curiosity kills the cat. It killed mine.
in ...29... I set the default value to 50, but not in config.xml, but in "Config" (web-based). Then everything was displayed (ie 'All'). I set it back to 25, Saved the Config, and still see all items. 
So far, there seems to be no way to go back to the 25 via Config.

My config.xml is void of any setting like yours, though derived from the autogenerated one by gerbera. The web UI has in all cases returned a blue status bar, informed me of a successful update.

**Comment by KarlStraussberger** [comment] 2024-11-18 22:35
Once you used the web ui content view, you always get the last setting on revisit.

The default only kicks in if you open the web ui for the first time or in private mode.

**Comment by nobanzai** [comment] 2024-11-19 09:29
Ok, so I can remove some cookies on the client or some config file on the server to start over?

**Comment by KarlStraussberger** [comment] 2024-11-19 09:38
> Ok, so I can remove some cookies on the client or some config file on the server to start over?

You have to clear the localstorage for your gerbera host.

**Comment by nobanzai** [comment] 2024-11-19 10:09
Thx.

**Comment by nobanzai** [comment] 2024-11-19 10:28
Uh, on more question - where do I find this localstorage on the host? Is it part of the darabase?

**Comment by KarlStraussberger** [comment] 2024-11-19 10:36
> Uh, one more question - where do I find this localstorage on the host? Is it part of the darabase?

It's in the browser F12>Web-Storage>Local Storage

**Comment by nobanzai** [comment] 2024-11-19 11:01
"no data present for selected host"

**Comment by udippel** [comment] 2024-11-19 11:18
I find it somewhat strange, though. "WON'T FIX" would be better to describe this. Oh yes, it does work with cleaning the local storage, thanks, @KarlStraussberger.

Though it is a somewhat awkward and unusual and unexpected method. I guess that a configuration change in a web UI settings page would be expected to be reflected in the display; latest after a 'normal' reload. 
Chrome 130, e.g., doesn't have "Web Storage", there it is "Application".

(Again, only my personal 2 Cent here, if there is anything like this, I'd prefer to remove such settings. Better display a fixed number of items, or restrict it to config.xml, than confusing users; taking up everyone's time, including that of the developers.)

**Comment by nobanzai** [comment] 2024-11-19 11:34
Even removing all data and cookies for this site didn't change anything.

**Comment by udippel** [comment] 2024-11-19 11:40
What's your browser? Have you seen my earlier post? 
Eventually start another, new, browser.
Completely clean && reload (Ctrl+Shift+Del, if I'm not mistaken?) in your current one.

**Comment by nobanzai** [comment] 2024-11-19 12:25
My browser is Firefox on openSUSE Tumbleweed.
Stopping all browser windows and restarting firefox does not help, neither does Ctrl-Shift-Del.
Clicking on the lock icon left of the url field and "clear cookies and site data" was my first attempt, but also didn't succeed.
Even using falkon as browser for the first time only shows 25 items instead of the configured default of 50 in config.xml.

**Comment by udippel** [comment] 2024-11-19 12:51
Okay, I can confirm your issue. I tried on .... 31 ..., setting in the correct section of config.xml: <server>, <ui>, and despite of the `<items-per-page default="50">`, followed by a restart, and cleaning local storage, it displays 25 items.

**Comment by nobanzai** [comment] 2024-11-19 16:52
Thx!

**Comment by KarlStraussberger** [comment] 2024-11-19 17:08
To ease your pains, I added a small "*" after the default value, so we get both sides addressed: The user who does not want her settings changed and the admin who did the change.

**Comment by nobanzai** [comment] 2024-11-19 19:16
> To ease your pains,

:)

> I added a small "*" after the default value, so we get both sides addressed: The user who does not want her settings changed and the admin who did the change.

Thx!

**Closed** 2024-11-20 06:45 UTC

**Comment by udippel** [comment] 2024-11-21 10:05
Works, in ...36... . Happy? Not really. Restart of gerbera, reload made no difference. 
Fiddling with cache data (Developer Tools->Application->Local Storage->[delete] pageInfo->Reload) was necessary. Still think that's a tad unusual.
