### ISSUE TITLE
Gerbera won't start thru systemctl

### ISSUE THREAD

**Issue by ToontjeHoger2** [gerbera/gerbera#366] opened 2018-10-18 10:14 UTC
Finally I got gerbera installed on Raspberry Pi V3 with raspbian stretch. It starts using the command line: **/usr/local/bin/gerbera -c /etc/gerbera/config.xml.**
But it won't start thru systemctl: **sudo systemctl start gerbera**.
$ **sudo systemctl status gerbera                                     
● gerbera.service - Gerbera Media Server with MySQL 
 Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)                                          Active: activating (auto-restart) (Result: exit-code) since Thu 2018-10-18 11:44:52 CEST; 3s ago                            Process: 28041 ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAI                     Main PID: 28041 (code=exited, status=1/FAILURE)**

Does anyone have any clue?
Thank you, ToontjeHoger2

**Comment by elmodaddyb** [comment] 2018-10-18 10:35
Hello @ToontjeHoger2 -

Gerbera installs a systemd file that uses the user/group `gerbera` to launch the gerbera runtime. Similar to below.

```
User=gerbera
Group=gerbera
ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml
```

Can you try launching gerbera manually under the same user account used to launch the systemd daemon?

Instructions are found here for troubleshooting --> http://docs.gerbera.io/en/latest/daemon.html#troubleshooting

**Comment by ToontjeHoger2** [comment] 2018-10-18 18:08
Well,i did what you asked me to do (i followed the instructions in de Gerbera daemon section of the manual). This is the result:
**su gerbera
Password: 
$  /usr/local/bin/gerbera -c /etc/gerbera/config.xml
2018-10-18 19:36:35    INFO: Gerbera UPnP Server version 1.3.0alpha - http://gerbera.io/
2018-10-18 19:36:35    INFO: ===============================================================================
2018-10-18 19:36:35    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2018-10-18 19:36:35    INFO: Copyright 2016-2018 Gerbera Contributors.
2018-10-18 19:36:35    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2018-10-18 19:36:35    INFO: ===============================================================================
2018-10-18 19:36:35    INFO: Loading configuration from: /etc/gerbera/config.xml
2018-10-18 19:36:35    INFO: Checking configuration...
2018-10-18 19:36:35   ERROR: Permission denied: /home/loveMusic/.config/gerbera (errno: 130)**

A few notes:

- before i posted the issue i already created a user gerbera om my system without the --system flag. So i deleted that user and created one with the flag. This did not help.
- user gerbera should have writing permissions on /home/loveMusic/.config/gerbera so i chmod 777 the gerbera directory. This didn't help either.
- in can't find the gerbera service file in /etc/systemd/system/ but i found it in /etc/systemd/system/ multi-user.target.wants/, perhaps that's okee, i don't know...

Thanks for the help so far, but i need a little more, i'm afraid.

**Comment by elmodaddyb** [comment] 2018-10-19 23:36
@ToontjeHoger2 - Can you be sure that each folder is accessible by the `gerbera` user:

```bash
$ ls -ld /home && ls -ld /home/loveMusic && ls -ld /home/loveMusic/.config
```

Maybe this will reveal a parent folder for which `gerbera` user does not have permissions?

**Comment by ToontjeHoger2** [comment] 2018-10-22 16:47
Hi Eamonn, 

Thank you for helping me out. I made user _gerbera_ member of the group
_loveMusic_ so gerbera can access the folders you've suggested as is
shown in the first block of console outrput. 

But still no success, as shown below... 

Regards Ton 

SU GERBERA
PASSWORD: 
$ LS -LD /HOME && LS -LD /HOME/LOVEMUSIC && LS -LD
/HOME/LOVEMUSIC/.CONFIG
DRWXR-XR-X 3 ROOT ROOT 4096 MAY 4 15:53 /HOME
DRWXR-XR-X 15 LOVEMUSIC LOVEMUSIC 4096 OCT 20 00:31 /HOME/LOVEMUSIC
DRWX------ 8 LOVEMUSIC LOVEMUSIC 4096 OCT 16 22:14
/HOME/LOVEMUSIC/.CONFIG

SUDO SYSTEMCTL START GERBERA 
LOVEMUSIC@ABURASPIB2:~ $ SUDO SYSTEMCTL STATUS GERBERA 
● GERBERA.SERVICE - GERBERA MEDIA SERVER WITH MYSQL
 LOADED: LOADED (/LIB/SYSTEMD/SYSTEM/GERBERA.SERVICE; DISABLED; VENDOR
PRESET: ENABLED)
 ACTIVE: FAILED (RESULT: EXIT-CODE) SINCE SUN 2018-10-21 20:08:10 CEST;
3S AGO
 XPROCESS: 24220 EXECSTART=/USR/LOCAL/BIN/GERBERA -C
/ETC/GERBERA/CONFIG.XML (CODE=EXITED, STATUS=1/FAILURE)
 MAIN PID: 24220 (CODE=EXITED, STATUS=1/FAILURE) 

OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
GERBERA IS FREE SOFTWARE, COVERED BY THE GNU GENERAL PUBLIC LICENSE
VERSION 2
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
COPYRIGHT 2016-2018 GERBERA CONTRIBUTORS.
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
GERBERA IS BASED ON MEDIATOMB: COPYRIGHT 2005-2010 GENA BATSYAN, SERGEY
BOSTANDZHYAN, LEONHARD WIMMER.
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
===============================================================================
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
LOADING CONFIGURATION FROM: /ETC/GERBERA/CONFIG.XML
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 INFO:
CHECKING CONFIGURATION...
OCT 21 20:08:10 ABURASPIB2 GERBERA[24220]: 2018-10-21 20:08:10 ERROR:
PERMISSION DENIED: /HOME/LOVEMUSIC/.CONFIG/GERBERA (ERRNO: 130)
OCT 21 20:08:10 ABURASPIB2 SYSTEMD[1]: GERBERA.SERVICE: MAIN PROCESS
EXITED, CODE=EXITED, STATUS=1/FAILURE
OCT 21 20:08:10 ABURASPIB2 SYSTEMD[1]: GERBERA.SERVICE: UNIT ENTERED
FAILED STATE.
OCT 21 20:08:10 ABURASPIB2 SYSTEMD[1]: GERBERA.SERVICE: FAILED WITH
RESULT 'EXIT-CODE'. 

On 20-10-2018 01:36, Eamonn wrote:

> @ToontjeHoger2 [1] - Can you be sure that each folder is accessible by the gerbera user:
> 
> $ ls -ld /home && ls -ld /home/loveMusic && ls -ld /home/loveMusic/.config
> 
> Maybe this will reveal a parent folder for which gerbera user does not have permissions? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/ToontjeHoger2
[2] https://github.com/gerbera/gerbera/issues/366#issuecomment-431527440
[3]

**Comment by elmodaddyb** [comment] 2018-10-22 23:46
Maybe I reading it wrong, but it looks like `gerbera` as part of `lovemusic` group.  Does **not** have access to read the `.config` directory.
```
DRWX------ 8 LOVEMUSIC LOVEMUSIC 4096 OCT 16 22:14 /HOME/LOVEMUSIC/.CONFIG
```
This looks like only `lovemusic` can `R`ead/`W`rite/e`X`ecute the directory.  Other members of the group `lovemusic` (i.e. `gerbera`) cannot do anything.

On the `.config` directory, I would expect to see something like below:

```
DRWXRW---- 8 LOVEMUSIC LOVEMUSIC 4096 OCT 16 22:14 /HOME/LOVEMUSIC/.CONFIG
```

https://ss64.com/bash/chmod.html

Maybe something like....just guessing here... 🤞 
```
chmod g+rwx /home/lovemusic/.config/
```

**Comment by v00d00** [comment] 2018-10-28 10:14
As @elmodaddyb mentions, this looks like a permissions error, if you sort that it should be fine. But as such, not a bug, so closing.

**Closed by v00d00** 2018-10-28 10:14 UTC
