### ISSUE TITLE
basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#628] opened 2020-01-22 11:39 UTC
Hi there,

whenever I am trying to add a new media source (via gui or within the config.xml), gerbera service restarts and nothing else happens.
I tried using to build with DEBUG, but didn't get any other message apart from that:
```
gerbera[8991]: terminate called after throwing an instance of 'std::logic_error'
gerbera[8991]:   what():  basic_string::_M_construct null not valid

```

Have you got any Idea what that could be?

BR,
count

**Comment by whyman** [comment] 2020-01-22 11:52
Looks like a regular old bug. Can you try running it with `catchsegv` or gdb to get a backtrace?

**Comment by count00zero** [comment] 2020-01-22 12:05
same outcome with catchsegv:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

**Comment by pamapa** [comment] 2020-01-22 17:36
Looks like a std::string with null initialization bug. The Question is where :-) We already fixed some of them. I guess you are using latest master.
Can you configure cmake with with -DCMAKE_BUILD_TYPE=Debug. That should give us more information, when it crashes and use gdb.

I will try to reproduce it locally.

**Comment by count00zero** [comment] 2020-01-22 21:10
yes, I am using latest master and did configure cmake as you suggested.
The outcome looks like this:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```
I already used -DWITH_DEBUG=1 and now -DCMAKE_BUILD_TYPE=Debug didn't make a difference ...
Maybe I did something wrong ...

**Comment by whyman** [comment] 2020-01-23 19:43
Its not anything  you did wrong, just #630 wasnt merged yet.

Please try latest master.

**Comment by count00zero** [comment] 2020-01-23 20:13
same ol', same ol' :)

Even with -DWITH_DEBUG=1 and -DCMAKE_BUILD_TYPE=Debug and execution with catchsegv
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

**Closed** 2020-01-23 22:50 UTC

**Comment by count00zero** [comment] 2020-01-24 09:47
Thanks a lot ... u did it ;-)
