### ISSUE TITLE
Build warnings Gerbera 1.9.0 Dockerfile

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#1725] opened 2021-07-31 12:29 UTC
They are just warnings, nothing important. The base Alpine image uses GCC 10.2.1. Maybe it's related to #1674

* Execute `docker build -t gerbera/gerbera:1.9.0 .`
* You will the these errors:

```
[ 77%] Building CXX object CMakeFiles/libgerbera.dir/src/util/upnp_headers.cc.o
In file included from /usr/include/c++/10.2.1/vector:72,
                 from /gerbera_build/src/util/upnp_clients.h:36,
                 from /gerbera_build/src/util/upnp_clients.cc:27:
/usr/include/c++/10.2.1/bits/vector.tcc: In member function 'std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::_M_erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = ClientCacheEntry; _Alloc = std::allocator<ClientCacheEntry>]':
/usr/include/c++/10.2.1/bits/vector.tcc:184:5: note: parameter passing for argument of type 'std::vector<ClientCacheEntry>::iterator' changed in GCC 7.1
  184 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/10.2.1/bits/vector.tcc:184:5: note: parameter passing for argument of type 'std::vector<ClientCacheEntry>::iterator' changed in GCC 7.1
/usr/include/c++/10.2.1/bits/vector.tcc: In member function 'void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {ClientCacheEntry}; _Tp = ClientCacheEntry; _Alloc = std::allocator<ClientCacheEntry>]':
/usr/include/c++/10.2.1/bits/vector.tcc:426:7: note: parameter passing for argument of type 'std::vector<ClientCacheEntry>::iterator' changed in GCC 7.1
  426 |       vector<_Tp, _Alloc>::
      |       ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10.2.1/vector:67,
                 from /gerbera_build/src/util/upnp_clients.h:36,
                 from /gerbera_build/src/util/upnp_clients.cc:27:
/usr/include/c++/10.2.1/bits/stl_vector.h: In member function 'void Clients::updateCache(const sockaddr_storage*, const string&, const ClientInfo*)':
/usr/include/c++/10.2.1/bits/stl_vector.h:1461:17: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<ClientCacheEntry*, std::vector<ClientCacheEntry> >' changed in GCC 7.1
 1461 |  return _M_erase(__beg + (__first - __cbeg), __beg + (__last - __cbeg));
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10.2.1/vector:72,
                 from /gerbera_build/src/util/upnp_clients.h:36,
                 from /gerbera_build/src/util/upnp_clients.cc:27:
/usr/include/c++/10.2.1/bits/vector.tcc:121:21: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<ClientCacheEntry*, std::vector<ClientCacheEntry> >' changed in GCC 7.1
  121 |    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
      |    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by KarlStraussberger** [comment] 2021-07-31 16:04
As far as I learned this message is caused by a new compiler on an older environment. Can be fixed by updating more than just the compiler.

**Comment by neheb** [comment] 2021-08-11 22:23
This warning is specific to ARM platforms. It says that binaries are incompatible with libraries built with GCC6. It can safely be ignored.

**Comment by whyman** [comment] 2021-08-12 08:08
I dont think there is anything we can really do about this warning.

If anyone cares enough about silencing warnings about GCC6 to 7 migrations, then a PR with `-Wno-psabi` in the cases that this happen could be merged.

**Closed by whyman** 2021-08-12 08:08 UTC

**Comment by neheb** [comment] 2021-09-01 01:53
I looked into this just now. I think this can be fixed by calling remove() instead of erase(). There's just one big problem.

remove() returns void before C++20 and thus no way to check whether or not it removed anything. Maybe do a test before and after if end() is identical.
